### ISSUE TITLE
Raise `AppRegistryNotReady` on Django1.9

### ISSUE THREAD

**Issue by giginet** [lambdalisue/django-inspectional-registration#53]
```
Traceback (most recent call last):
  File "runtests.py", line 55, in <module>
    run_tests(base_dir)
  File "runtests.py", line 36, in run_tests
    django.setup()
  File "/Users/giginet/.ghq/github.com/lambdalisue/django-inspectional-registration/.tox/py34-django19/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/giginet/.ghq/github.com/lambdalisue/django-inspectional-registration/.tox/py34-django19/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/giginet/.ghq/github.com/lambdalisue/django-inspectional-registration/.tox/py34-django19/lib/python3.4/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/giginet/.ghq/github.com/lambdalisue/django-inspectional-registration/.tox/py34-django19/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "src/registration/supplements/__init__.py", line 11, in <module>
    from registration.supplements.base import RegistrationSupplementBase
  File "src/registration/supplements/base.py", line 14, in <module>
    class RegistrationSupplementBase(models.Model):
  File "/Users/giginet/.ghq/github.com/lambdalisue/django-inspectional-registration/.tox/py34-django19/lib/python3.4/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/giginet/.ghq/github.com/lambdalisue/django-inspectional-registration/.tox/py34-django19/lib/python3.4/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/giginet/.ghq/github.com/lambdalisue/django-inspectional-registration/.tox/py34-django19/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

It seems to be same with this issue.
https://github.com/lambdalisue/django-permission/issues/48

**Comment by lambdalisue** [comment]
Could you? @giginet

**Comment by giginet** [comment]
OK
I'll try it.
