### ISSUE TITLE
ImportError: cannot import name RequestSite

### ISSUE THREAD

**Issue by thomas-maurice** [lambdalisue/django-inspectional-registration#57]
Hello !

There seems to be an issue with the app with django 1.9.1.

When I try to launch the migrations :
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/thomas/.local/share/virtualenvs/djangossl/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/thomas/.local/share/virtualenvs/djangossl/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/thomas/.local/share/virtualenvs/djangossl/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/thomas/.local/share/virtualenvs/djangossl/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/thomas/.local/share/virtualenvs/djangossl/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/thomas/.local/share/virtualenvs/djangossl/lib/python2.7/site-packages/registration/models.py", line 63, in <module>
    from registration.utils import generate_activation_key
  File "/home/thomas/.local/share/virtualenvs/djangossl/lib/python2.7/site-packages/registration/utils.py", line 9, in <module>
    from django.contrib.sites.models import RequestSite
ImportError: cannot import name RequestSite
```

There seems to ba a fix there : https://stackoverflow.com/questions/34250597/importerror-cannot-import-name-requestsite-when-inlude-registration-in-instal

Thanks :)

**Comment by giginet** [comment]
It would be fixed on #55.
However, this is not contained in latest release.
@lambdalisue We have to release newer version.

@thomas-maurice if you would like to use this plugin on 1.9.x, you should use HEAD version instead of latest on PyPI. Sorry for the inconvenience.

**Comment by lambdalisue** [comment]
https://pypi.python.org/pypi/django-inspectional-registration
v0.6.0 is now available

**Comment by thomas-maurice** [comment]
Thanks ! :) nice job !
